AllCops:
  NewCops: enable
  Exclude:
    - '*'
    - 'bin/*'
    - 'config/**/*'
    - 'config/*'
    - 'db/*'
    - 'lib/**/*'
    - 'log/*'
    - 'public/*'
    - 'storage/*'
    - 'tmp/**/*'
    - 'tmp/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
